name: C/C++ CI

on:
  pull_request:
    branches:    
      - main
      - 'dryka-development'
  push:
    branches: 
      - main
      - 'dryka-development'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run build script
      run: |
         chmod +x scripts/Build.sh
         scripts/Build.sh
      shell: bash
  
  test:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run test script
      run: |
         chmod +x scripts/Build.sh
         scripts/Build.sh
         chmod +x scripts/Test.sh
         scripts/Test.sh
      shell: bash
